apiVersion: v1
kind: Service
metadata:
  name: {{ include "traffic.fullname" . }}
  labels:
    {{- include "traffic.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: traffic
      protocol: TCP
      name: traffic
  selector:
    {{- include "traffic.selectorLabels" . | nindent 4 }}
